import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUiProvider } from "@/lib/providers/NextUIProvider";
import MyContextProvider from "@/lib/providers/MyContextProvider";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MyContextProvider>
          <ReduxStoreProvider>
            <NextUiProvider>
            <Toaster />
              <div className="text-[#02060A]">{children}</div>
            </NextUiProvider>
          </ReduxStoreProvider>
        </MyContextProvider>
      </body>
    </html>
  );
}
