import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUiProvider } from "@/lib/providers/NextUIProvider";
import MyContextProvider from "@/lib/providers/MyContextProvider";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={` ${inter.className} antialiased`}
      >
        <MyContextProvider>
          <ReduxStoreProvider>
            <NextUiProvider>
            <Toaster />
              <div className="text-[#02060A]">{children}</div>
            </NextUiProvider>
          </ReduxStoreProvider>
        </MyContextProvider>
      </body>
    </html>
  );
}
